package sessionio

import (
	"encoding/json"
	"strings"
	"testing"
)

// The three shapes of harness bookkeeping, as they are actually written.
// Counts measured across 354 transcripts on this box, 2026-09-02.
const (
	// 15 records. The receipt for a slash command, with the SGR codes the CLI
	// drew it with, and two lines of hook chatter — one of which carries the
	// hook's entire command (2,206 of the 2,402 characters).
	realStdout = "<local-command-stdout>\x1b[2mCompacted (ctrl+o to see full summary)\x1b[22m\n" +
		"\x1b[2mPreCompact [/home/wizard/.claude/hooks/pre-compact-backup.sh] completed successfully\x1b[22m\n" +
		"\x1b[2mPostCompact [if [ -z \"${HOME-}\" ]; then printf '{}\\n'; fi] completed successfully: {}\x1b[22m" +
		"</local-command-stdout>"
	// 18 records, marked isMeta. A fixed sentence addressed to the model.
	realCaveat = "<local-command-caveat>Caveat: The messages below were generated by the user " +
		"while running local commands. DO NOT respond to these messages or otherwise consider " +
		"them in your response unless the user explicitly asks you to.</local-command-caveat>"
	// 583 records — the most common single shape of harness markup in the
	// corpus. Every one of the 583 carries a <summary>.
	realTaskNotification = "<task-notification>\n<task-id>boe4u3lz5</task-id>\n" +
		"<tool-use-id>toolu_01Diw2cn5Sm1gn6GMUkQLBeM</tool-use-id>\n" +
		"<output-file>/tmp/claude-1000/x/tasks/boe4u3lz5.output</output-file>\n" +
		"<status>completed</status>\n" +
		"<summary>Background command \"Capture live lexical baseline\" completed (exit code 0)</summary>\n" +
		"</task-notification>"
)

// harnessRow classifies a user-role record that is the harness talking to
// itself. None of these are prompts, and rendered as prompts they are what
// Viktor reported on 2026-09-02: angle-bracket tags and escape bytes in the
// chat where a person's words should be.
func TestHarnessRow(t *testing.T) {
	for _, tc := range []struct {
		name string
		in   string
		want string
		ok   bool
	}{
		{
			name: "a background task finishing is worth its summary line",
			in:   realTaskNotification,
			want: `Background command "Capture live lexical baseline" completed (exit code 0)`,
			ok:   true,
		},
		{
			// The caveat is addressed to the model and says nothing to a
			// reader, so it earns no row at all.
			name: "the local-command caveat is dropped whole",
			in:   realCaveat,
			ok:   true,
		},
		{
			name: "a command receipt keeps what it says and loses the escapes",
			in:   realStdout,
			want: "Compacted (ctrl+o to see full summary)",
			ok:   true,
		},
		{
			name: "a receipt with nothing but hook chatter earns no row",
			in: "<local-command-stdout>\x1b[2mPreCompact [/home/wizard/.claude/hooks/x.sh] " +
				"completed successfully\x1b[22m</local-command-stdout>",
			ok: true,
		},
		{
			name: "a model change is a receipt worth reading",
			in: "<local-command-stdout>Set model to \x1b[1mOpus 5 (1M context)\x1b[22m and saved " +
				"as your default for new sessions\x1b[2m\x1b[22m\n\x1b[2m     Managed settings " +
				"pins \x1b[1mOpus 5\x1b[22m\x1b[2m — that applies on restart\x1b[22m</local-command-stdout>",
			want: "Set model to Opus 5 (1M context) and saved as your default for new sessions\n" +
				"     Managed settings pins Opus 5 — that applies on restart",
			ok: true,
		},
		{
			// Markup with no summary in it: better no row than an empty one.
			// None of the 583 measured lacked one, so this is a guard rather
			// than a case seen in the wild.
			name: "a task notification with no summary earns no row",
			in:   "<task-notification>\n<task-id>x</task-id>\n<status>completed</status>\n</task-notification>",
			ok:   true,
		},
		{name: "an ordinary prompt is not harness markup", in: "deploy the thing", ok: false},
		{
			name: "prose that merely mentions the tag is left alone",
			in:   "grep for <task-notification> in the source",
			ok:   false,
		},
		{name: "empty", in: "", ok: false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, _, ok := harnessRow(tc.in)
			if ok != tc.ok {
				t.Fatalf("ok = %v, want %v (got %q)", ok, tc.ok, got)
			}
			if got != tc.want {
				t.Errorf("harnessRow() = %q, want %q", got, tc.want)
			}
		})
	}
}

// plainText is what stands between a terminal's control bytes and a chat row.
// In a browser an escape sequence is not formatting: it is a replacement glyph
// followed by its parameters as literal text.
func TestPlainText(t *testing.T) {
	for _, tc := range []struct{ name, in, want string }{
		{name: "text with nothing to strip is returned as it is", in: "hello world", want: "hello world"},
		{name: "SGR codes go", in: "\x1b[2mdim\x1b[22m", want: "dim"},
		{name: "an SGR code with several parameters goes", in: "\x1b[1;31;40mred\x1b[0m", want: "red"},
		{
			// A progress bar redraws itself with a cursor move and a
			// line-erase: 51 tool results in the corpus carry these.
			name: "cursor moves and line erases go, the carriage return stays",
			in:   "done\n\r\x1b[Knext",
			want: "done\n\rnext",
		},
		{
			name: "an OSC title runs to its terminator and no further",
			in:   "\x1b]0;a title\x07after",
			want: "after",
		},
		{
			name: "an OSC terminated by ST rather than BEL",
			in:   "\x1b]52;;Zm9v\x1b\\after",
			want: "after",
		},
		{
			// Two prompts in the corpus were submitted with the line editor's
			// key bytes still in front of them.
			name: "stray control bytes in a prompt go, the words stay",
			in:   "\x05\x15I am at KFC with my girlfriend",
			want: "I am at KFC with my girlfriend",
		},
		{
			name: "tabs and newlines are layout, not control",
			in:   "a\tb\nc\r\nd",
			want: "a\tb\nc\r\nd",
		},
		{name: "DEL goes", in: "ab\x7fc", want: "abc"},
		{name: "a trailing escape with nothing after it goes", in: "text\x1b", want: "text"},
		{
			// The failure mode this exists to avoid: an unterminated OSC must
			// not swallow the rest of somebody's message.
			name: "an unterminated OSC costs its introducer, not the line",
			in:   "\x1b]0;never terminated\nthe rest of the message",
			want: "0;never terminated\nthe rest of the message",
		},
		{
			name: "a malformed CSI costs its introducer, not the line",
			in:   "\x1b[émigré still readable",
			want: "émigré still readable",
		},
		{
			name: "multi-byte characters are untouched",
			in:   "\x1b[2mémigré → 日本語\x1b[22m",
			want: "émigré → 日本語",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := plainText(tc.in); got != tc.want {
				t.Errorf("plainText(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// A receipt is bounded: the hook filter is a pattern, so a shape it does not
// recognise must still not become a wall.
func TestCommandReceiptIsBounded(t *testing.T) {
	line, _, ok := harnessRow("<local-command-stdout>" + strings.Repeat("x", 4096) + "</local-command-stdout>")
	if !ok {
		t.Fatal("not recognised as harness markup")
	}
	if len(line) > 1<<10+64 {
		t.Errorf("receipt is %d bytes, want it bounded near 1 KiB", len(line))
	}
	if !strings.Contains(line, "truncated") {
		t.Errorf("a cut receipt must say so: %q", line[len(line)-40:])
	}
}

// A slash command the CLI answers itself opens a turn nothing can ever close.
//
// Claude Code records the command as an ordinary user-role record whose text is
// <command-name> markup. Every test the normalizer has for "the human spoke"
// says yes to it, so it starts a turn — but for a command the CLI handles
// locally the model is never called, no assistant record with a terminal
// stop_reason ever arrives, and nothing closes the turn. The text view draws a
// working row for as long as the last turn is open, so the session claims to be
// working with nothing running, until the operator's next real prompt.
//
// Measured across the 357 session transcripts on this box on 2026-09-04: 16
// command records were answered locally (/model 6, /compact 5, /effort 5) and
// every one of them held its turn open. The longest stretch was 31.6 hours, in
// the session this was reported from, and what finally closed it was Viktor
// typing the bug report about it.
//
// The receipt is the transcript's own evidence that the command is over: the
// CLI writes <local-command-stdout> once it has printed the command's output
// and gone back to the prompt. For /compact that lands 2.5 minutes after the
// command record — real work, and it shows as working for exactly as long as it
// runs.
func TestCommandReceiptSettlesTheTurnTheCommandOpened(t *testing.T) {
	// json.Marshal rather than a string literal: the receipt carries the SGR
	// codes the CLI drew it with, and a raw control byte inside a JSON string is
	// invalid JSON — the record would fail to decode, which reads as the
	// normalizer dropping it.
	user := func(at string, isMeta bool, text string) []byte {
		b, err := json.Marshal(map[string]any{
			"type":      "user",
			"isMeta":    isMeta,
			"timestamp": at,
			"message":   map[string]any{"role": "user", "content": text},
		})
		if err != nil {
			t.Fatalf("fixture: %v", err)
		}
		return b
	}

	n := NewNormalizer("demo")
	var out []Event
	add := func(evs []Event) { out = append(out, evs...) }

	// The five records are the ones the reported session actually holds, in
	// order (transcript 716469e6, records 13176-13178 preceded by a settled
	// turn).
	add(n.Line(user("2026-09-02T19:40:00.000Z", false, "hello")))
	add(n.Line([]byte(`{"type":"assistant","timestamp":"2026-09-02T19:40:05.000Z","message":{"id":"m1","role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"hi"}]}}`)))
	add(n.Line(user("2026-09-02T19:48:23.996Z", true, realCaveat)))
	add(n.Line(user("2026-09-02T19:48:23.996Z", false, "<command-name>/compact</command-name>\n<command-message>compact</command-message>")))
	receiptAt := len(out)
	add(n.Line(user("2026-09-02T19:50:50.440Z", false, realStdout)))

	// The command opened a turn of its own; the prompt before it kept its own.
	first, last := out[0].TurnID, out[len(out)-1].TurnID
	if first == "" || last == "" || first == last {
		t.Fatalf("want the command in a turn of its own, got %q then %q: %v", first, last, kinds(out))
	}
	// The receipt still says what the command printed.
	if got := out[receiptAt]; got.Kind != KindState || !strings.Contains(got.Body, "Compacted") {
		t.Fatalf("receipt row = %+v", got)
	}
	var ended bool
	for _, e := range out[receiptAt:] {
		if e.Kind == KindTurnEnd && e.TurnID == last {
			ended = true
		}
	}
	if !ended {
		t.Fatalf("the command's turn %s is still open after its receipt: %v", last, kinds(out[receiptAt:]))
	}
	// Settled stays settled. A turn_end per receipt would end the same turn
	// twice, and the renderer folds a turn on the first one.
	before := len(out)
	add(n.Line(user("2026-09-02T19:50:51.000Z", false, realStdout)))
	for _, e := range out[before:] {
		if e.Kind == KindTurnEnd {
			t.Fatalf("a second receipt emitted another turn_end: %v", kinds(out[before:]))
		}
	}
}

// A command the model answers keeps its turn open, because the model is
// genuinely working on it. /wrap-up, /implement and the other skill commands
// are recorded as the same <command-name> markup and write no receipt at all:
// 47 of the 63 command records in the corpus are these. Settling on the markup
// rather than on the receipt would end their turn before the reply arrived.
func TestASkillCommandKeepsItsTurnOpen(t *testing.T) {
	n := NewNormalizer("demo")
	out := n.Line([]byte(`{"type":"user","timestamp":"2026-09-02T19:40:00.000Z","message":{"role":"user","content":"<command-name>/wrap-up</command-name>"}}`))
	if len(out) != 1 || out[0].Kind != KindUser || out[0].Body != "/wrap-up" {
		t.Fatalf("command row = %+v", out)
	}
	out = append(out, n.Line([]byte(`{"type":"assistant","timestamp":"2026-09-02T19:40:09.000Z","message":{"id":"m2","role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"wrapped"}]}}`))...)
	if got := kinds(out); len(got) != 3 || got[2] != KindTurnEnd {
		t.Fatalf("want the model's reply to be what ends the turn, got %v", got)
	}
}

// End to end: the three shapes must reach the renderer as muted status lines,
// and must NOT open a turn. A background task finishing is not the operator
// speaking, and 583 of them across the corpus each split the transcript into a
// new turn attributed to a wall of XML.
func TestHarnessRecordsDoNotOpenATurn(t *testing.T) {
	n := &Normalizer{}
	// A real prompt first, so there is a turn to stay inside.
	evs := n.Line([]byte(`{"type":"user","message":{"role":"user","content":"do the thing"},` +
		`"timestamp":"2026-09-02T10:00:00.000Z","sessionId":"x","uuid":"u1"}`))
	if len(evs) != 1 || evs[0].Kind != KindUser {
		t.Fatalf("prompt: got %+v", evs)
	}
	turn := evs[0].TurnID
	if turn == "" {
		t.Fatal("the prompt opened no turn")
	}

	for _, tc := range []struct {
		name string
		body string
		want string
		// A command receipt ENDS the open turn as well as staying inside it —
		// it is the CLI reporting that the command it was handling is done (see
		// TestCommandReceiptSettlesTheTurnTheCommandOpened). A task
		// notification is a background job reporting in and says nothing about
		// the turn.
		wantEnd bool
	}{
		{name: "task notification", body: realTaskNotification,
			want: `Background command "Capture live lexical baseline" completed (exit code 0)`},
		{name: "command receipt", body: realStdout,
			want: "Compacted (ctrl+o to see full summary)", wantEnd: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			line, err := json.Marshal(map[string]any{
				"type":      "user",
				"message":   map[string]any{"role": "user", "content": tc.body},
				"timestamp": "2026-09-02T10:00:01.000Z",
				"sessionId": "x",
				"uuid":      "u2",
			})
			if err != nil {
				t.Fatal(err)
			}
			evs := n.Line(line)
			want := 1
			if tc.wantEnd {
				want = 2
			}
			if len(evs) != want {
				t.Fatalf("got %d events, want %d: %+v", len(evs), want, evs)
			}
			if evs[0].Kind != KindState {
				t.Errorf("kind = %q, want %q", evs[0].Kind, KindState)
			}
			if evs[0].TurnID != turn {
				t.Errorf("turn = %q, want the prompt's turn %q", evs[0].TurnID, turn)
			}
			if evs[0].Body != tc.want {
				t.Errorf("body = %q, want %q", evs[0].Body, tc.want)
			}
			if tc.wantEnd && (evs[1].Kind != KindTurnEnd || evs[1].TurnID != turn) {
				t.Errorf("second event = %+v, want a turn_end in %q", evs[1], turn)
			}
		})
	}

	t.Run("caveat", func(t *testing.T) {
		line, err := json.Marshal(map[string]any{
			"type":      "user",
			"isMeta":    true,
			"message":   map[string]any{"role": "user", "content": realCaveat},
			"timestamp": "2026-09-02T10:00:02.000Z",
			"sessionId": "x",
			"uuid":      "u3",
		})
		if err != nil {
			t.Fatal(err)
		}
		if evs := n.Line(line); len(evs) != 0 {
			t.Errorf("got %d events, want none: %+v", len(evs), evs)
		}
	})
}

// A prompt reaches the chat as the operator's own words, control bytes and all
// removed — and an ordinary prompt is untouched.
func TestPromptIsPlainText(t *testing.T) {
	n := &Normalizer{}
	line, err := json.Marshal(map[string]any{
		"type":      "user",
		"message":   map[string]any{"role": "user", "content": "\x05\x15I am at KFC"},
		"timestamp": "2026-09-02T10:00:00.000Z",
		"sessionId": "x",
		"uuid":      "u1",
	})
	if err != nil {
		t.Fatal(err)
	}
	evs := n.Line(line)
	if len(evs) != 1 || evs[0].Kind != KindUser {
		t.Fatalf("got %+v", evs)
	}
	if evs[0].Body != "I am at KFC" {
		t.Errorf("body = %q, want %q", evs[0].Body, "I am at KFC")
	}
}

// A tool result renders from the structured `stdout` in preference to the
// flattened body, so stripping only the body left the colour codes on screen.
// 911 of 49,896 tool results in the corpus carry them.
func TestToolResultOutputIsPlainText(t *testing.T) {
	n := &Normalizer{}
	const coloured = "\x1b[32mok\x1b[0m"
	line, err := json.Marshal(map[string]any{
		"type": "user",
		"message": map[string]any{"role": "user", "content": []any{
			map[string]any{"type": "tool_result", "tool_use_id": "t1", "content": coloured},
		}},
		"toolUseResult": map[string]any{"stdout": coloured, "stderr": "", "interrupted": false},
		"timestamp":     "2026-09-02T10:00:00.000Z",
		"sessionId":     "x",
		"uuid":          "u1",
	})
	if err != nil {
		t.Fatal(err)
	}
	var got *Event
	for _, e := range n.Line(line) {
		if e.Kind == KindToolResult {
			e := e
			got = &e
		}
	}
	if got == nil {
		t.Fatal("no tool_result event")
	}
	if got.Body != "ok" {
		t.Errorf("body = %q, want %q", got.Body, "ok")
	}
	var res struct {
		Stdout      string `json:"stdout"`
		Interrupted bool   `json:"interrupted"`
	}
	if err := json.Unmarshal(got.Result, &res); err != nil {
		t.Fatalf("result is not an object: %v (%s)", err, got.Result)
	}
	if res.Stdout != "ok" {
		t.Errorf("result.stdout = %q, want %q", res.Stdout, "ok")
	}
	if res.Interrupted {
		t.Error("interrupted flipped — fields other than stdout/stderr must survive")
	}
}

// A result with nothing to strip must come back byte-for-byte: 98% of them, and
// re-marshalling every one would reorder keys for no reason.
func TestCleanResultIsUntouched(t *testing.T) {
	raw := json.RawMessage(`{"stdout":"plain","stderr":"","interrupted":false,"z":1}`)
	if got := plainResult(raw); string(got) != string(raw) {
		t.Errorf("plainResult() = %s, want it unchanged", got)
	}
}

// JSON does not spell every control byte \u00XX: backspace and form feed get
// the short escapes, and testing for \u00 alone let 6 results through with a
// stray form feed still in them (measured across the corpus, 2026-09-02).
func TestPlainResultSeesTheShortEscapes(t *testing.T) {
	for _, tc := range []struct{ name, in, wantStdout string }{
		{name: "form feed", in: `{"stdout":"a\fb"}`, wantStdout: "ab"},
		{name: "backspace", in: `{"stdout":"a\bb"}`, wantStdout: "ab"},
		{name: "NUL", in: `{"stdout":"a\u0000b"}`, wantStdout: "ab"},
		{name: "escape", in: `{"stdout":"a\u001b[2mb"}`, wantStdout: "ab"},
		{name: "newlines survive", in: `{"stdout":"a\nb"}`, wantStdout: "a\nb"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var got struct{ Stdout string }
			if err := json.Unmarshal(plainResult(json.RawMessage(tc.in)), &got); err != nil {
				t.Fatal(err)
			}
			if got.Stdout != tc.wantStdout {
				t.Errorf("stdout = %q, want %q", got.Stdout, tc.wantStdout)
			}
		})
	}
}
