package release

// One declaration of who may use this box, rendered into the two files the
// services read.
//
// This exists for installs with no roster. On the homelab devvm, roster.yaml
// and t3-provision-users.sh own /etc/ttyd-user-map and /etc/sudoers.d/ttyd-users
// and reconcile them hourly; a self-hoster has neither and today writes both by
// hand, keeping them in step by remembering to. One file removes that.
//
// The important constraint is what this must NOT become. A second writer on a
// box whose roster already owns those files is exactly the shape that revoked
// two users' terminals on 2026-08-29 — a generated copy overwriting a live one.
// `tl-users apply` refuses to run where the roster is present; see cmd/tl-users.

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// User is one row: the name the proxy sends, and the account it means.
type User struct {
	// Identity is what TL_AUTH_HEADER carries. Matched on its local part, so
	// "alice" and "alice@example.com" are the same person to the services.
	Identity string
	// OSUser is the account on this box.
	OSUser string
}

// osUserRe bounds the account name. Same charset as the act-as target in
// authuser, including the refusal of a leading dash: this value reaches
// `sudo -u <user>` argv, where a leading dash reads as a flag, and a
// /home/<user> path.
var osUserRe = regexp.MustCompile(`^[a-zA-Z0-9_][a-zA-Z0-9_-]{0,31}$`)

// identityRe is deliberately wider — proxies emit addresses, and the local part
// is what gets matched — but still refuses whitespace and the separator.
var identityRe = regexp.MustCompile(`^[^\s=]{1,128}$`)

// ParseUsers reads the declaration. Format is "<identity> = <os_user>", one per
// line, # comments and blanks ignored.
//
// Every malformed line is an error rather than a skip. A skipped line is how
// someone discovers they have no access by failing to log in, with nothing in
// any log to say why.
func ParseUsers(text string) ([]User, error) {
	var out []User
	seenIdentity := map[string]bool{}
	seenOSUser := map[string]bool{}

	for n, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Split(line, "=")
		if len(parts) != 2 {
			return nil, fmt.Errorf("line %d: want '<identity> = <os_user>', got %q", n+1, line)
		}
		identity := strings.TrimSpace(parts[0])
		osUser := strings.TrimSpace(parts[1])
		if !identityRe.MatchString(identity) {
			return nil, fmt.Errorf("line %d: %q is not a usable identity", n+1, identity)
		}
		if !osUserRe.MatchString(osUser) {
			return nil, fmt.Errorf(
				"line %d: %q is not a usable account name (letters, digits, _ and -, "+
					"not starting with a dash, at most 32 characters)", n+1, osUser)
		}
		if seenIdentity[identity] {
			return nil, fmt.Errorf("line %d: %q is declared twice", n+1, identity)
		}
		// Two identities for one account would let either of them act as the
		// other's sessions without anything saying so.
		if seenOSUser[osUser] {
			return nil, fmt.Errorf("line %d: account %q is already claimed by another identity", n+1, osUser)
		}
		seenIdentity[identity] = true
		seenOSUser[osUser] = true
		out = append(out, User{Identity: identity, OSUser: osUser})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].OSUser < out[j].OSUser })
	return out, nil
}

const generatedBy = "# Generated by `tl-users apply` from %s — DO NOT EDIT BY HAND.\n"

// RenderUserMap produces /etc/ttyd-user-map, the same format the roster derives
// and the services parse.
func RenderUserMap(users []User) string {
	var b strings.Builder
	fmt.Fprintf(&b, generatedBy, LocalUsersPath)
	b.WriteString("# <identity>=<os_user>; the identity is matched on its local part.\n")
	for _, u := range users {
		fmt.Fprintf(&b, "%s=%s\n", u.Identity, u.OSUser)
	}
	return b.String()
}

// RenderSudoers produces /etc/sudoers.d/ttyd-users: one grant per non-service
// user, plus the root grant for the wrapper scripts.
//
// serviceUser is whoever the units run as. It is the left side of every grant
// and never a target of one — a grant to become yourself is meaningless, and it
// reads as though the service needed privilege it does not.
func RenderSudoers(users []User, serviceUser string) string {
	var b strings.Builder
	fmt.Fprintf(&b, generatedBy, LocalUsersPath)
	b.WriteString("# Install at /etc/sudoers.d/ttyd-users (mode 0440, owner root:root).\n")
	b.WriteString("#\n")
	b.WriteString("# Lets the service user become each OTHER account, for a fixed set of\n")
	b.WriteString("# binaries. Never (ALL): this is the boundary between two people's\n")
	b.WriteString("# accounts on one machine.\n")
	for _, u := range users {
		if u.OSUser == serviceUser {
			continue
		}
		fmt.Fprintf(&b, "%s ALL=(%s) NOPASSWD: %s\n",
			serviceUser, u.OSUser, strings.Join(sudoUserCommands, ", "))
	}
	fmt.Fprintf(&b, "%s ALL=(root) NOPASSWD: %s\n",
		serviceUser, strings.Join(sudoRootCommands, ", "))
	return b.String()
}

// What the service may run as another account. Kept in step with the roster's
// own list in infra/scripts/workstation/roster_engine.py: the services are the
// same, so the grant is.
var sudoUserCommands = []string{
	"/usr/bin/tmux",
	"/usr/local/bin/tmux-user-attach",
	"/usr/local/bin/tmux-user-dirlist",
	"/usr/local/bin/file-api",
	"/usr/local/bin/session-events",
	"/usr/local/bin/skills-api",
}

// What it may run as root: the three wrappers that need privilege of their own.
// Each validates its arguments against the user map, so the grant is narrow in
// what it can be pointed at as well as in what it can run.
var sudoRootCommands = []string{
	"/usr/local/bin/tmux-restore-user",
	"/usr/local/bin/tmux-user-setfacl",
	"/usr/local/bin/tmux-persist-forget",
}

// LocalUsersPath is the declaration an operator edits.
const LocalUsersPath = "/etc/terminal-lobby.users"

// RosterMarker is what a roster-generated file says about itself. terminal-lobby
// does not parse a roster; it only needs to recognise that something else owns
// these files and stand down.
const RosterMarker = "roster.yaml"

// RosterOwns reports the first of paths whose content claims a roster generated
// it, or "" when none does.
//
// This is the guard that stops tl-users becoming a second writer. A generated
// copy overwriting a live one is what revoked two users' terminals on
// 2026-08-29, and a tool that quietly did the same would be that bug again.
// Reading the file rather than probing for the roster is deliberate: it works on
// a box that has never heard of this homelab, and it is the file itself that
// says who owns it.
func RosterOwns(paths ...string) string {
	for _, p := range paths {
		b, err := os.ReadFile(p)
		if err == nil && strings.Contains(string(b), RosterMarker) {
			return p
		}
	}
	return ""
}
