#!/usr/bin/env python3
"""Vendor xterm.js + addons into frontend/index.html, transpiled for old WebKit.

Why this exists
---------------
xterm.js 6.0.0 ships ES2022 class static blocks (`class X { static { ... } }`),
which Safari only parses from 16.4. iPadOS 15.8 — the last release some iPads
take — runs a Safari 15.6-era engine, and *every* browser on iOS/iPadOS uses
that system WebKit, so a Chrome-version bump cannot help. A static block is a
PARSE-time SyntaxError there, so the whole bundle fails to evaluate,
`window.Terminal` never gets defined, and the terminal pane stays empty while
the rest of the lobby (inline script, no xterm dependency) keeps working.

xterm 5.5.0 had zero static blocks, which is why this only started with the
5.5.0 -> 6.0.0 upgrade (e80fa6d, 2026-07-13).

What it does
------------
Downloads each pinned asset, verifies it against the published sha384 (the
same supply-chain check the old SRI attributes gave us), transpiles the JS to
BASELINE with esbuild, and splices the result into frontend/index.html between
the VENDOR markers. Self-hosting also removes the runtime dependency on
cdn.jsdelivr.net.

Run it when bumping xterm or an addon; the output is committed, so deploys and
the dev harness need no build step and stay byte-identical to what is reviewed.
"""
from __future__ import annotations

import base64
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# TL_INDEX aims this at a page other than the vanilla one — the same knob
# scripts/test_frontend_compat.py uses, so vendoring a page and then checking it
# name the target the same way. frontend/term.html is the second page that
# mounts xterm (the terminal the v2 SPA frames), and it needs the identical
# transpiled bundle: iPadOS 15.8 ships a WebKit that cannot PARSE xterm 6's
# `static{}` blocks, so a CDN-loaded xterm there is a blank terminal on that
# device, exactly as it was on the vanilla page before it was vendored.
INDEX = os.environ.get("TL_INDEX") or os.path.join(REPO, "frontend", "index.html")

# esbuild target. Floor is set by the oldest engine we serve: iPadOS 15.8.
BASELINE = "safari15"

GEN = "generated by scripts/vendor-xterm.py — do not edit by hand"
CSS_BEGIN = f"<!-- BEGIN VENDOR CSS ({GEN}) -->"
CSS_END = "<!-- END VENDOR CSS -->"
JS_BEGIN = f"<!-- BEGIN VENDOR JS ({GEN}) -->"
JS_END = "<!-- END VENDOR JS -->"

BASE = "https://cdn.jsdelivr.net/npm"

# (kind, url, sha384). Load ORDER matters: xterm.js defines the Terminal the
# addons attach to. Hashes are the published ones from the non-.min paths —
# jsdelivr re-minifies .min files over time, so those are not hash-stable.
ASSETS = [
    ("css", f"{BASE}/@xterm/xterm@6.0.0/css/xterm.css",
     "sha384-n2n7twoohnW+d3myBKaUgl7DSiwidw6MkQy9oesGzkPpMjejKRR3XlnD+5yCdtBD"),
    ("js", f"{BASE}/@xterm/xterm@6.0.0/lib/xterm.js",
     "sha384-f/1U6Z9wM4D71a5eRXEZnyOTMOvjqxr2XLwh+Go1OvIl3L3tOcvUrzudnhbECwl4"),
    ("js", f"{BASE}/@xterm/addon-fit@0.11.0/lib/addon-fit.js",
     "sha384-txoiwu4RR2GD3qySbaj+BbzibkLbSJRcfqGYMu6z1EqHil4A2dyBiBW5dlacG6OR"),
    ("js", f"{BASE}/@xterm/addon-web-links@0.12.0/lib/addon-web-links.js",
     "sha384-0IIwkXq0LAkIxEVKxlOxWbje2g/VT+5CzVTZiEukyiZ02pOl/O+M0fkpEKAYqto9"),
    ("js", f"{BASE}/@xterm/addon-webgl@0.19.0/lib/addon-webgl.js",
     "sha384-8/2DNT7OeuMQVc7wBPoMHAQ+NmEoYSx27k7IdbsItiomGC5D9+LTrbo8jtY6YZv8"),
    ("js", f"{BASE}/@xterm/addon-clipboard@0.2.0/lib/addon-clipboard.js",
     "sha384-w58/aoMoWyj3vL47sXkN/bnchsdCAHHUQslw59i9Ei276OIuUCZgAO5y07Db60Bg"),
    ("js", f"{BASE}/@xterm/addon-image@0.9.0/lib/addon-image.js",
     "sha384-A0PSF1Lj/V7OlfamYmcJj3t0ncwvdrr98hHE84Byzdlov+oKltItc43WKEcQZUb5"),
    ("js", f"{BASE}/@xterm/addon-unicode11@0.9.0/lib/addon-unicode11.js",
     "sha384-s7G1tpQVHxwemnFdH7ZEOPEAMxRSbFGsvrhaHpxYuMssFdike2DQuIBzg43+p5/3"),
]


def find_esbuild() -> list[str]:
    local = os.path.join(REPO, "frontend-v2", "node_modules", ".bin", "esbuild")
    if os.path.isfile(local):
        return [local]
    if shutil.which("esbuild"):
        return ["esbuild"]
    if shutil.which("npx"):
        return ["npx", "--yes", "esbuild@0.25.12"]
    sys.exit("vendor-xterm: need esbuild (frontend-v2/node_modules, PATH, or npx)")


def fetch(url: str, want: str) -> bytes:
    with urllib.request.urlopen(url, timeout=60) as r:
        body = r.read()
    got = "sha384-" + base64.b64encode(hashlib.sha384(body).digest()).decode()
    if got != want:
        sys.exit(f"vendor-xterm: sha384 mismatch for {url}\n  want {want}\n  got  {got}")
    return body


def transpile(esbuild: list[str], src: bytes, name: str) -> str:
    with tempfile.TemporaryDirectory() as td:
        inp = os.path.join(td, name)
        with open(inp, "wb") as f:
            f.write(src)
        out = subprocess.run(
            esbuild + [inp, f"--target={BASELINE}", "--minify", "--log-level=warning"],
            capture_output=True, check=True,
        )
        if out.stderr.strip():
            sys.stderr.write(out.stderr.decode())
        return out.stdout.decode()


def splice(html: str, begin: str, end: str, block: str) -> str:
    if begin not in html or end not in html:
        sys.exit(f"vendor-xterm: markers {begin!r}/{end!r} not found in {INDEX}")
    return html[:html.index(begin)] + block + html[html.index(end) + len(end):]


def main() -> None:
    esbuild = find_esbuild()
    css: list[str] = [CSS_BEGIN]
    js: list[str] = [JS_BEGIN]
    js.append(f"    <!-- xterm + addons, transpiled to {BASELINE} so iPadOS 15.8 WebKit "
              "can parse them (see this script's docstring). Load order matters. -->")

    for kind, url, sha in ASSETS:
        name = url.rsplit("/", 1)[-1]
        body = fetch(url, sha)
        print(f"  fetched {name} ({len(body)} bytes, sha384 ok)")
        if kind == "css":
            css.append(f"    <style>/* {url} */\n{body.decode()}</style>")
            continue
        code = transpile(esbuild, body, name)
        left = len(re.findall(r"\bstatic\s*\{", code))
        if left:
            sys.exit(f"vendor-xterm: {name} still has {left} class static blocks "
                     f"after transpiling to {BASELINE} — refusing to ship it")
        print(f"    transpiled -> {len(code)} bytes, 0 static blocks")
        js.append(f"    <script>/* {url} (transpiled to {BASELINE}) */\n{code}</script>")

    css.append("    " + CSS_END)
    js.append("    " + JS_END)

    with open(INDEX, encoding="utf-8") as f:
        html = f.read()
    html = splice(html, CSS_BEGIN, CSS_END, "\n".join(css))
    html = splice(html, JS_BEGIN, JS_END, "\n".join(js))
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"vendor-xterm: {INDEX} is now {len(html)} bytes")


if __name__ == "__main__":
    main()
